// @ts-check
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import prettier from 'eslint-config-prettier';

/**
 * Flat ESLint config for the monorepo.
 *
 * The `no-explicit-any` rule is an error everywhere; parse boundaries that genuinely need `any`
 * disable it inline with a justification comment, which the constitution requires.
 * Import-boundary enforcement (Principle II) lives in `.dependency-cruiser.cjs`, not here, so the
 * same rules run in CI independently of the linter.
 */
export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.next/**',
      '**/.turbo/**',
      '**/coverage/**',
      '**/playwright-report/**',
      '**/test-results/**',
      'packages/client/src/generated.ts',
      // Generated by `next build`; its triple-slash reference is Next's, not ours to restyle.
      '**/next-env.d.ts',
      // A k6 script: it runs in k6's own runtime with `__ENV` and `k6/*` modules, not in Node.
      'tools/loadtest/**',
      '.specify/**',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    // Config files that must stay CommonJS (dependency-cruiser reads `.cjs`).
    files: ['**/*.cjs'],
    languageOptions: {
      sourceType: 'commonjs',
      globals: { module: 'writable', require: 'readonly' },
    },
  },
  {
    rules: {
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/consistent-type-imports': ['error', { prefer: 'type-imports' }],
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      'no-restricted-syntax': [
        'error',
        {
          selector: "NewExpression[callee.name='Date'][arguments.length=0]",
          message:
            'Read the current instant through the injected Clock port, never `new Date()` — the voting window must be decided from one server-time source (SC-007).',
        },
        {
          selector: "CallExpression[callee.object.name='Date'][callee.property.name='now']",
          message:
            'Read the current instant through the injected Clock port, never `Date.now()` (SC-007).',
        },
      ],
      eqeqeq: ['error', 'always'],
      'no-console': ['error', { allow: ['warn', 'error'] }],
    },
  },
  {
    // The Clock implementation and CLI/scripts are the only places allowed to read the wall clock.
    files: [
      'packages/db/src/clock.ts',
      'tools/**/*.ts',
      'scripts/**/*.ts',
      'apps/web/src/server/clock.ts',
      // JWT issued-at/expiry are token lifetimes, not the voting window. The window is decided
      // exclusively by core/window from the injected Clock (SC-007).
      'apps/web/src/server/admin-auth.ts',
      'apps/web/src/server/voter-cookie.ts',
    ],
    rules: { 'no-restricted-syntax': 'off', 'no-console': 'off' },
  },
  {
    files: ['**/*.test.ts', '**/*.test.tsx', 'tests/**/*.ts', 'apps/web/tests/**/*.ts'],
    rules: { 'no-restricted-syntax': 'off', 'no-console': 'off' },
  },
  prettier,
);
