/* eslint-disable */
// AUTO-GENERATED by scripts/generate-client.ts — DO NOT EDIT.
//
// Regenerate with `pnpm generate:client`. The source of truth is the endpoint registry in
// packages/contracts/src/endpoints.ts; editing this file by hand is overwritten on the next run and
// silently breaks the guarantee that every client speaks the same contract (Principle III).
//
// Generated 8 operations.

import type { z } from 'zod';
import * as contracts from '@padelmigas/contracts';

/** Response and payload types, derived from the Zod schemas rather than restated. */
export namespace C {
  export type ListTournamentsResponse = z.output<(typeof contracts.ENDPOINTS)[0]['response']>;
  export type ListTournamentsQuery = z.input<NonNullable<(typeof contracts.ENDPOINTS)[0]['query']>>;
  export type GetTournamentDetailResponse = z.output<(typeof contracts.ENDPOINTS)[1]['response']>;
  export type CastBallotResponse = z.output<(typeof contracts.ENDPOINTS)[2]['response']>;
  export type CastBallotBody = z.input<NonNullable<(typeof contracts.ENDPOINTS)[2]['body']>>;
  export type GetGroupResultsResponse = z.output<(typeof contracts.ENDPOINTS)[3]['response']>;
  export type GetPlayerResponse = z.output<(typeof contracts.ENDPOINTS)[4]['response']>;
  export type PreviewLineupResponse = z.output<(typeof contracts.ENDPOINTS)[5]['response']>;
  export type PreviewLineupBody = z.input<NonNullable<(typeof contracts.ENDPOINTS)[5]['body']>>;
  export type PublishTournamentResponse = z.output<(typeof contracts.ENDPOINTS)[6]['response']>;
  export type PublishTournamentBody = z.input<NonNullable<(typeof contracts.ENDPOINTS)[6]['body']>>;
  export type SyncRankingsResponse = z.output<(typeof contracts.ENDPOINTS)[7]['response']>;
}

export interface ClientConfig {
  /**
   * Base URL including the version prefix, e.g. `/api/v1` in the browser or
   * `https://host/api/v1` from a native client. Versioned by construction: a v2 client is a
   * different base URL, never a conditional inside this one (Principle III).
   */
  readonly baseUrl: string;
  /** Injected so a React Native client can supply its own; defaults to global `fetch`. */
  readonly fetch?: typeof fetch;
  /** Extra headers applied to every request. Never used for a voter identifier (FR-022). */
  readonly headers?: Readonly<Record<string, string>>;
}

/** An error response from the API, carrying the stable `code` clients branch on. */
export class ApiRequestError extends Error {
  readonly status: number;
  readonly code: contracts.ErrorCode | 'NETWORK_ERROR';
  readonly issues: readonly contracts.ErrorIssue[];

  constructor(
    status: number,
    code: contracts.ErrorCode | 'NETWORK_ERROR',
    message: string,
    issues: readonly contracts.ErrorIssue[] = [],
  ) {
    super(message);
    this.name = 'ApiRequestError';
    this.status = status;
    this.code = code;
    this.issues = issues;
  }
}

function toSearchParams(query: unknown): string {
  if (query === null || query === undefined) return '';
  const search = new URLSearchParams();
  for (const [key, value] of Object.entries(query as Record<string, unknown>)) {
    if (value === null || value === undefined) continue;
    search.set(key, String(value));
  }
  return search.toString();
}

interface RequestOptions {
  readonly method: string;
  readonly url: string;
  readonly body?: unknown;
  readonly voterDependent: boolean;
}

async function request(config: ClientConfig, options: RequestOptions): Promise<unknown> {
  const doFetch = config.fetch ?? globalThis.fetch;
  const headers: Record<string, string> = { Accept: 'application/json', ...config.headers };
  if (options.body !== undefined) headers['Content-Type'] = 'application/json';
  // A voter-dependent response must not be stored by anything between the server and the screen.
  // Sent as a request header rather than the browser-only init.cache option: the header is
  // portable to React Native and is typed everywhere. The server also answers no-store; the pair
  // is deliberate belt-and-braces against Risk R1.
  if (options.voterDependent) headers['Cache-Control'] = 'no-store';

  let response: Response;
  try {
    response = await doFetch(`${config.baseUrl}${options.url}`, {
      method: options.method,
      headers,
      // The voter cookie is httpOnly and must ride along on every call (ADR-004).
      credentials: 'include',
      ...(options.body === undefined ? {} : { body: JSON.stringify(options.body) }),
    });
  } catch {
    throw new ApiRequestError(0, 'NETWORK_ERROR', 'Não foi possível contactar o servidor.', []);
  }

  if (response.status === 204) return undefined;

  let payload: unknown;
  try {
    payload = await response.json();
  } catch {
    payload = undefined;
  }

  if (!response.ok) {
    const envelope = (payload ?? {}) as {
      code?: contracts.ErrorCode;
      message?: string;
      issues?: contracts.ErrorIssue[];
    };
    throw new ApiRequestError(
      response.status,
      envelope.code ?? 'INTERNAL_ERROR',
      envelope.message ?? `Request failed with status ${response.status}.`,
      envelope.issues ?? [],
    );
  }

  return payload;
}

/** Creates a typed client. One instance per base URL; safe to share across a process. */
export function createClient(config: ClientConfig) {
  return {
  /**
   * List published tournaments.
   *
   * `GET /api/v1/tournaments` — FR-023.
   * Documented failures: MALFORMED_PAYLOAD.
   */
  async listTournaments(params: { query?: C.ListTournamentsQuery }): Promise<C.ListTournamentsResponse> {
    const path = `/tournaments`;
    const search = toSearchParams(params.query);
    const url = search ? `${path}?${search}` : path;
    return request(config, {
      method: 'GET',
      url,
      voterDependent: false,
    }) as Promise<C.ListTournamentsResponse>;
  },
  /**
   * Tournament detail with groups, pairs, the caller's vote state, and results where revealed.
   *
   * `GET /api/v1/tournaments/{slug}` — FR-014, FR-015, FR-020, FR-021.
   * Voter-dependent: the server sends `no-store` and this call is never cached.
   * Documented failures: NOT_FOUND.
   */
  async getTournamentDetail(params: { slug: string }): Promise<C.GetTournamentDetailResponse> {
    const path = `/tournaments/${encodeURIComponent(String(params.slug))}`;
    const url = path;
    return request(config, {
      method: 'GET',
      url,
      voterDependent: true,
    }) as Promise<C.GetTournamentDetailResponse>;
  },
  /**
   * Cast this voter's single ballot for a group.
   *
   * `POST /api/v1/groups/{groupId}/ballots` — FR-009, FR-010, FR-011, FR-012, FR-013, SC-005.
   * Voter-dependent: the server sends `no-store` and this call is never cached.
   * Documented failures: INCOMPLETE_BALLOT, DUPLICATE_POSITION, UNKNOWN_PAIR, MISSING_PAIR, ALREADY_VOTED, VOTING_CLOSED, NOT_FOUND, RATE_LIMITED, MALFORMED_PAYLOAD.
   */
  async castBallot(params: { groupId: string; body: C.CastBallotBody }): Promise<C.CastBallotResponse> {
    const path = `/groups/${encodeURIComponent(String(params.groupId))}/ballots`;
    const url = path;
    return request(config, {
      method: 'POST',
      url,
      body: params.body,
      voterDependent: true,
    }) as Promise<C.CastBallotResponse>;
  },
  /**
   * Crowd results for one group, subject to the reveal gate.
   *
   * `GET /api/v1/groups/{groupId}/results` — FR-016, FR-017, FR-018, FR-019, FR-020, FR-021.
   * Voter-dependent: the server sends `no-store` and this call is never cached.
   * Documented failures: RESULTS_HIDDEN, NOT_FOUND.
   */
  async getGroupResults(params: { groupId: string }): Promise<C.GetGroupResultsResponse> {
    const path = `/groups/${encodeURIComponent(String(params.groupId))}/results`;
    const url = path;
    return request(config, {
      method: 'GET',
      url,
      voterDependent: true,
    }) as Promise<C.GetGroupResultsResponse>;
  },
  /**
   * A player and every tournament appearance.
   *
   * `GET /api/v1/players/{playerId}` — FR-025.
   * Documented failures: NOT_FOUND.
   */
  async getPlayer(params: { playerId: string }): Promise<C.GetPlayerResponse> {
    const path = `/players/${encodeURIComponent(String(params.playerId))}`;
    const url = path;
    return request(config, {
      method: 'GET',
      url,
      voterDependent: false,
    }) as Promise<C.GetPlayerResponse>;
  },
  /**
   * Validate a lineup payload and return the derived tournament without persisting it.
   *
   * `POST /api/v1/admin/tournaments/preview` — FR-001, FR-002, FR-003, FR-004, FR-005.
   * Documented failures: UNRESOLVED_PLAYERS, MALFORMED_PAYLOAD, START_NOT_IN_FUTURE, DUPLICATE_PLAYER, POINTS_MISMATCH, INVALID_GROUP_SIZE, SLUG_TAKEN, UNAUTHORISED.
   */
  async previewLineup(params: { body: C.PreviewLineupBody }): Promise<C.PreviewLineupResponse> {
    const path = `/admin/tournaments/preview`;
    const url = path;
    return request(config, {
      method: 'POST',
      url,
      body: params.body,
      voterDependent: false,
    }) as Promise<C.PreviewLineupResponse>;
  },
  /**
   * Publish a previously previewed lineup.
   *
   * `POST /api/v1/admin/tournaments` — FR-002, FR-006, FR-007, FR-008.
   * Documented failures: UNRESOLVED_PLAYERS, MALFORMED_PAYLOAD, START_NOT_IN_FUTURE, DUPLICATE_PLAYER, POINTS_MISMATCH, INVALID_GROUP_SIZE, NOT_CONFIRMED, SLUG_TAKEN, UNAUTHORISED.
   */
  async publishTournament(params: { body: C.PublishTournamentBody }): Promise<C.PublishTournamentResponse> {
    const path = `/admin/tournaments`;
    const url = path;
    return request(config, {
      method: 'POST',
      url,
      body: params.body,
      voterDependent: false,
    }) as Promise<C.PublishTournamentResponse>;
  },
  /**
   * Import the public ranking sheet into players and rating snapshots.
   *
   * `POST /api/v1/admin/rankings/sync` — FR-004, FR-007.
   * Documented failures: DUPLICATE_MATCH_KEY, UNAUTHORISED.
   */
  async syncRankings(_params?: undefined): Promise<C.SyncRankingsResponse> {
    const path = '/admin/rankings/sync';
    const url = path;
    return request(config, {
      method: 'POST',
      url,
      voterDependent: false,
    }) as Promise<C.SyncRankingsResponse>;
  },
  };
}

export type ApiClient = ReturnType<typeof createClient>;
