/**
 * Generates `packages/client/src/generated.ts` from the endpoint registry in `packages/contracts`.
 *
 * The constitution requires clients to consume a generated client and forbids hand-rolled fetch
 * calls or hard-coded URLs outside it (Principle III). Generating from the same table the OpenAPI
 * document comes from is what keeps `apps/web` and a future `apps/mobile` provably in step.
 *
 * The emitted module is fetch-only: no framework, no state library, no workspace imports beyond the
 * contract types themselves.
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  ENDPOINTS as RAW_ENDPOINTS,
  type EndpointDefinition,
} from '../packages/contracts/src/endpoints.js';

// `ENDPOINTS` is declared `as const satisfies` so the emitted types can index it literally. Here we
// only iterate, so widen to the interface — otherwise optional keys absent from some entries are
// unreachable on the narrowed union.
const ENDPOINTS: readonly EndpointDefinition[] = RAW_ENDPOINTS;

const OUTPUT = join(process.cwd(), 'packages', 'client', 'src', 'generated.ts');

/** `listTournaments` → `ListTournaments`, for building type names. */
function pascal(value: string): string {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

/** `/groups/{groupId}/ballots` → a template literal with the params interpolated. */
function pathExpression(endpoint: EndpointDefinition): string {
  const withParams = endpoint.path.replace(
    /\{(\w+)\}/g,
    (_match: string, name: string) => `\${encodeURIComponent(String(params.${name}))}`,
  );
  return `\`${withParams}\``;
}

function argsType(endpoint: EndpointDefinition): string {
  const parts: string[] = [];
  for (const param of endpoint.pathParams) parts.push(`${param}: string`);
  if (endpoint.query) parts.push(`query?: C.${pascal(endpoint.operationId)}Query`);
  if (endpoint.body) parts.push(`body: C.${pascal(endpoint.operationId)}Body`);
  return parts.length === 0 ? 'Record<never, never>' : `{ ${parts.join('; ')} }`;
}

function operation(endpoint: EndpointDefinition): string {
  const name = endpoint.operationId;
  const hasArgs =
    endpoint.pathParams.length > 0 || Boolean(endpoint.query) || Boolean(endpoint.body);
  const paramsBinding = hasArgs ? 'params: ' + argsType(endpoint) : '_params?: undefined';

  const lines: string[] = [];
  lines.push(`  /**`);
  lines.push(`   * ${endpoint.summary}.`);
  lines.push(`   *`);
  lines.push(
    `   * \`${endpoint.method} /api/v1${endpoint.path}\` — ${endpoint.requirements.join(', ')}.`,
  );
  if (endpoint.voterDependent) {
    lines.push(
      `   * Voter-dependent: the server sends \`no-store\` and this call is never cached.`,
    );
  }
  lines.push(`   * Documented failures: ${endpoint.errors.join(', ')}.`);
  lines.push(`   */`);
  lines.push(`  async ${name}(${paramsBinding}): Promise<C.${pascal(name)}Response> {`);
  lines.push(`    const path = ${hasArgs ? pathExpression(endpoint) : `'${endpoint.path}'`};`);
  if (endpoint.query) {
    lines.push(`    const search = toSearchParams(params.query);`);
    lines.push(`    const url = search ? \`\${path}?\${search}\` : path;`);
  } else {
    lines.push(`    const url = path;`);
  }
  lines.push(`    return request(config, {`);
  lines.push(`      method: '${endpoint.method}',`);
  lines.push(`      url,`);
  if (endpoint.body) lines.push(`      body: params.body,`);
  lines.push(`      voterDependent: ${String(endpoint.voterDependent)},`);
  lines.push(`    }) as Promise<C.${pascal(name)}Response>;`);
  lines.push(`  },`);
  return lines.join('\n');
}

function typeAliases(): string {
  const lines: string[] = [];
  for (const endpoint of ENDPOINTS) {
    const name = pascal(endpoint.operationId);
    if (endpoint.query) {
      lines.push(
        `export type ${name}Query = z.input<typeof contracts.ENDPOINTS[${ENDPOINTS.indexOf(endpoint)}]['query']>;`,
      );
    }
  }
  return lines.join('\n');
}

function header(): string {
  return `/* eslint-disable */
// AUTO-GENERATED by scripts/generate-client.ts — DO NOT EDIT.
//
// Regenerate with \`pnpm generate:client\`. The source of truth is the endpoint registry in
// packages/contracts/src/endpoints.ts; editing this file by hand is overwritten on the next run and
// silently breaks the guarantee that every client speaks the same contract (Principle III).
//
// Generated ${ENDPOINTS.length} operations.
`;
}

function body(): string {
  return `
import type { z } from 'zod';
import * as contracts from '@padelmigas/contracts';

/** Response and payload types, derived from the Zod schemas rather than restated. */
export namespace C {
${ENDPOINTS.map((endpoint, index) => {
  const name = pascal(endpoint.operationId);
  const lines = [
    `  export type ${name}Response = z.output<(typeof contracts.ENDPOINTS)[${index}]['response']>;`,
  ];
  if (endpoint.query) {
    lines.push(
      `  export type ${name}Query = z.input<NonNullable<(typeof contracts.ENDPOINTS)[${index}]['query']>>;`,
    );
  }
  if (endpoint.body) {
    lines.push(
      `  export type ${name}Body = z.input<NonNullable<(typeof contracts.ENDPOINTS)[${index}]['body']>>;`,
    );
  }
  return lines.join('\n');
}).join('\n')}
}

export interface ClientConfig {
  /**
   * Base URL including the version prefix, e.g. \`/api/v1\` in the browser or
   * \`https://host/api/v1\` from a native client. Versioned by construction: a v2 client is a
   * different base URL, never a conditional inside this one (Principle III).
   */
  readonly baseUrl: string;
  /** Injected so a React Native client can supply its own; defaults to global \`fetch\`. */
  readonly fetch?: typeof fetch;
  /** Extra headers applied to every request. Never used for a voter identifier (FR-022). */
  readonly headers?: Readonly<Record<string, string>>;
}

/** An error response from the API, carrying the stable \`code\` clients branch on. */
export class ApiRequestError extends Error {
  readonly status: number;
  readonly code: contracts.ErrorCode | 'NETWORK_ERROR';
  readonly issues: readonly contracts.ErrorIssue[];

  constructor(
    status: number,
    code: contracts.ErrorCode | 'NETWORK_ERROR',
    message: string,
    issues: readonly contracts.ErrorIssue[] = [],
  ) {
    super(message);
    this.name = 'ApiRequestError';
    this.status = status;
    this.code = code;
    this.issues = issues;
  }
}

function toSearchParams(query: unknown): string {
  if (query === null || query === undefined) return '';
  const search = new URLSearchParams();
  for (const [key, value] of Object.entries(query as Record<string, unknown>)) {
    if (value === null || value === undefined) continue;
    search.set(key, String(value));
  }
  return search.toString();
}

interface RequestOptions {
  readonly method: string;
  readonly url: string;
  readonly body?: unknown;
  readonly voterDependent: boolean;
}

async function request(config: ClientConfig, options: RequestOptions): Promise<unknown> {
  const doFetch = config.fetch ?? globalThis.fetch;
  const headers: Record<string, string> = { Accept: 'application/json', ...config.headers };
  if (options.body !== undefined) headers['Content-Type'] = 'application/json';
  // A voter-dependent response must not be stored by anything between the server and the screen.
  // Sent as a request header rather than the browser-only init.cache option: the header is
  // portable to React Native and is typed everywhere. The server also answers no-store; the pair
  // is deliberate belt-and-braces against Risk R1.
  if (options.voterDependent) headers['Cache-Control'] = 'no-store';

  let response: Response;
  try {
    response = await doFetch(\`\${config.baseUrl}\${options.url}\`, {
      method: options.method,
      headers,
      // The voter cookie is httpOnly and must ride along on every call (ADR-004).
      credentials: 'include',
      ...(options.body === undefined ? {} : { body: JSON.stringify(options.body) }),
    });
  } catch {
    throw new ApiRequestError(0, 'NETWORK_ERROR', 'Não foi possível contactar o servidor.', []);
  }

  if (response.status === 204) return undefined;

  let payload: unknown;
  try {
    payload = await response.json();
  } catch {
    payload = undefined;
  }

  if (!response.ok) {
    const envelope = (payload ?? {}) as {
      code?: contracts.ErrorCode;
      message?: string;
      issues?: contracts.ErrorIssue[];
    };
    throw new ApiRequestError(
      response.status,
      envelope.code ?? 'INTERNAL_ERROR',
      envelope.message ?? \`Request failed with status \${response.status}.\`,
      envelope.issues ?? [],
    );
  }

  return payload;
}

/** Creates a typed client. One instance per base URL; safe to share across a process. */
export function createClient(config: ClientConfig) {
  return {
${ENDPOINTS.map(operation).join('\n')}
  };
}

export type ApiClient = ReturnType<typeof createClient>;
`;
}

function main(): void {
  const source = header() + body();
  writeFileSync(OUTPUT, source, 'utf8');
  console.log(`Generated ${OUTPUT} — ${ENDPOINTS.length} operations.`);
  void typeAliases;
}

main();
