-- 0001_initial_schema.sql
--
-- Initial schema for group standings voting.
-- Source of truth: specs/001-group-standings-voting/data-model.md
--
-- Every instant is timestamptz in UTC; presentation in Europe/Lisbon happens in the client
-- (constitution: Locale & time). Group state is never stored — it is derived from
-- published_at + starts_at by the single `window` module in packages/core (Risk R5).

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------------------------------
-- players — one row per real person, never a denormalised "pair" string (FR-008)
-- ---------------------------------------------------------------------------------------------
create table players (
  id            uuid primary key default gen_random_uuid(),
  -- The ranking sheet's ID column is the canonical external identity (FR-004, ADR-007).
  external_id   integer     not null unique,
  display_name  text        not null check (length(btrim(display_name)) > 0),
  -- NFC -> case-folded -> whitespace-collapsed name. Generated by packages/core/matching and
  -- never by SQL, so every host normalises identically.
  match_key     text        not null unique check (length(btrim(match_key)) > 0),
  club          text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

comment on column players.match_key is
  'Normalised name produced by packages/core/matching. Never computed in SQL — see ADR-007.';

-- ---------------------------------------------------------------------------------------------
-- player_ratings — dated rating snapshots taken from the sheet's dated columns
-- ---------------------------------------------------------------------------------------------
create table player_ratings (
  player_id  uuid    not null references players (id) on delete cascade,
  rated_on   date    not null,
  points     integer not null check (points >= 0),
  -- Composite PK makes re-running a sync idempotent (FR-004).
  primary key (player_id, rated_on)
);

-- ---------------------------------------------------------------------------------------------
-- tournaments
-- ---------------------------------------------------------------------------------------------
create table tournaments (
  id           uuid primary key default gen_random_uuid(),
  name         text        not null check (length(btrim(name)) >= 3),
  slug         text        not null unique check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  -- Also the voting deadline (FR-011).
  starts_at    timestamptz not null,
  -- NULL means draft: never publicly visible.
  published_at timestamptz,
  created_at   timestamptz not null default now(),
  -- A tournament cannot be published into a window that has already closed (FR-005).
  constraint tournaments_published_before_start
    check (published_at is null or published_at < starts_at)
);

-- ---------------------------------------------------------------------------------------------
-- groups
-- ---------------------------------------------------------------------------------------------
create table groups (
  id            uuid primary key default gen_random_uuid(),
  tournament_id uuid     not null references tournaments (id) on delete cascade,
  label         text     not null check (length(btrim(label)) > 0),
  -- 1-based display order.
  position      smallint not null check (position >= 1),
  unique (tournament_id, label),
  unique (tournament_id, position)
);

-- Group size is deliberately not stored; it is count(pairs), validated at publish time to be
-- between 3 and 6 by packages/core/lineup (research D10).

-- ---------------------------------------------------------------------------------------------
-- pairs
-- ---------------------------------------------------------------------------------------------
create table pairs (
  id               uuid primary key default gen_random_uuid(),
  group_id         uuid     not null references groups (id) on delete cascade,
  player_1_id      uuid     not null references players (id),
  player_2_id      uuid     not null references players (id),
  club             text     not null check (length(btrim(club)) > 0),
  -- Points captured at publish time, so a later ranking sync never rewrites history (FR-007).
  player_1_points  integer  not null check (player_1_points >= 0),
  player_2_points  integer  not null check (player_2_points >= 0),
  total_points     integer  not null check (total_points >= 0),
  -- 1-based rank within the group.
  seed             smallint not null check (seed >= 1),
  unique (group_id, seed),
  constraint pairs_distinct_players check (player_1_id <> player_2_id),
  -- The payload supplies total_points and packages/core/lineup validates it; the constraint keeps
  -- the two honest at rest as well.
  constraint pairs_total_is_sum check (total_points = player_1_points + player_2_points)
);

-- A player appearing in two pairs of the same tournament is rejected in packages/core/lineup
-- before insert. Expressing it in SQL needs a trigger, which is not warranted at this scale
-- (data-model.md).

-- ---------------------------------------------------------------------------------------------
-- voters — anonymous cookie holders (ADR-004)
-- ---------------------------------------------------------------------------------------------
create table voters (
  id           uuid primary key default gen_random_uuid(),
  created_at   timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

comment on table voters is
  'Anonymous voter identities. No IP, no user agent, no personal data (constitution: Privacy). '
  'Rate limiting keys on a salted IP hash held outside Postgres with a 10-minute TTL.';

-- ---------------------------------------------------------------------------------------------
-- ballots — one immutable ballot per voter per group (FR-013)
-- ---------------------------------------------------------------------------------------------
create table ballots (
  id       uuid primary key default gen_random_uuid(),
  group_id uuid        not null references groups (id) on delete cascade,
  voter_id uuid        not null references voters (id),
  cast_at  timestamptz not null default now(),
  -- The concurrency guarantee behind SC-009 / Risk R7: two simultaneous submissions produce
  -- exactly one ballot, and the loser surfaces as ALREADY_VOTED rather than a 500.
  unique (group_id, voter_id)
);

-- No updated_at: ballots are insert-only (spec assumption).

-- ---------------------------------------------------------------------------------------------
-- ballot_entries — one row per ranked pair (ADR-005)
-- ---------------------------------------------------------------------------------------------
create table ballot_entries (
  ballot_id uuid     not null references ballots (id) on delete cascade,
  pair_id   uuid     not null references pairs (id),
  position  smallint not null check (position between 1 and 6),
  -- A pair cannot be ranked twice.
  primary key (ballot_id, pair_id),
  -- A position cannot be reused (FR-010).
  unique (ballot_id, position)
);

-- Completeness (every pair in the group ranked, positions forming 1..n) is validated in
-- packages/core/ballot; the whole ballot is inserted in one transaction, so a rejected ballot
-- leaves nothing behind.

-- ---------------------------------------------------------------------------------------------
-- group_final_standings — reserved, unpopulated (FR-026)
-- ---------------------------------------------------------------------------------------------
create table group_final_standings (
  group_id    uuid        not null references groups (id) on delete cascade,
  pair_id     uuid        not null references pairs (id),
  position    smallint    not null check (position between 1 and 6),
  recorded_at timestamptz not null default now(),
  primary key (group_id, pair_id),
  unique (group_id, position)
);

comment on table group_final_standings is
  'Reserved for real final standings (FR-026). Written by nothing in phase 1 and read by nothing; '
  'tests/architecture/reserved-tables.test.ts asserts no source file references it (Principle V).';

-- ---------------------------------------------------------------------------------------------
-- updated_at maintenance
-- ---------------------------------------------------------------------------------------------
create function set_updated_at() returns trigger
  language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger players_set_updated_at
  before update on players
  for each row
  execute function set_updated_at();

-- rollback:
-- drop trigger if exists players_set_updated_at on players;
-- drop function if exists set_updated_at();
-- drop table if exists group_final_standings;
-- drop table if exists ballot_entries;
-- drop table if exists ballots;
-- drop table if exists voters;
-- drop table if exists pairs;
-- drop table if exists groups;
-- drop table if exists tournaments;
-- drop table if exists player_ratings;
-- drop table if exists players;
-- -- pgcrypto is left in place: other migrations and the Supabase project may rely on it.
